### ISSUE TITLE
issues with mbbi/mbbo 

### ISSUE THREAD

**Issue by rerpha** [wanglin86769/node-epics-ca#3]
Hi @wanglin86769 
I am struggling to get the string value (ie. if RVAL is 1 then VAL is ONST) for an [mbbi ](https://epics.anl.gov/EpicsDocumentation/AppDevManuals/RecordRef/Recordref-23.html)or an [mbbo](https://epics.anl.gov/EpicsDocumentation/AppDevManuals/RecordRef/Recordref-25.html) record. String values seem to work for waveforms, stringin etc. 

Have you managed to get this working by adding things to the record itself, or using a field instead? Maybe I am doing something incorrectly. Just trying to get the PV or PV.VAL doesn't seem to work.

**Comment by wanglin86769** [comment]
Hi, 
Thanks for reporting.

I have published version 0.2.3 to support reading the string value for ENUM data type.  A new argument named **asString** with the default false value is added to get(), put() and monitor() methods, and passing true to asString will request string value from EPICS IOC.

The string value support can be used as follows,

get()
```
const CA = require('node-epics-ca');
(async () => {
    try {
        console.log(await CA.get('calcExample', true));
    } catch (error) {
        console.error(`get failed due to ${error}`);
    }
})()
```

put()
```
const CA = require('node-epics-ca');
(async () => {
    try {
        console.log(await CA.get('calcExample'));
        await CA.put("calcExample", 'One', true);
        console.log(await CA.get('calcExample'));
    } catch (error) {
        console.error(`put failed due to ${error}`);
    }
})()
```

monitor()
```
const CA = require('node-epics-ca');
(async () => {
    CA.monitor('calcExample', function(data) {
        console.log('Current:', data);
    }, true);
    // Test purpose only, prevent the node.js main thread from exiting
    setTimeout(function() {
        console.log("Done!!!");
    }, 3600 * 1000);
})()
```

**Comment by rerpha** [comment]
Great, thank you very much, will test out soon.

**Comment by rerpha** [comment]
Works well, thanks.
